name: CH11
version: 0.1.0.0
github: "jonathanlorimer/CH11"
license: BSD3
author: "Jonathan Lorimer"
maintainer: "jonathan_lorimer@mac.com"
copyright: "2019 Jonathan Lorimer"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/jonathanlorimer/CH11#readme>

dependencies:
  - base >= 4.7 && < 5
  - split

library:
  source-dirs: src

executables:
  CH11-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - CH11

tests:
  CH11-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - CH11
